export const mockEpisods = [
  {
    "air_date": "2019-04-06",
    "episode_number": 1,
    "episode_type": "standard",
    "id": 1675448,
    "name": "Cruelty",
    "overview": "It is the Taisho Period (i.e. 1912-1926). Tanjiro Kamado is living a modest but blissful life in the mountains with his family. One day, when he returns from selling charcoal in town, he finds the remains of his slaughtered family in pools of blood after a demon attack. Tanjiro rushes down the snowy mountain with the sole survivor, his sister Nezuko, on his back. But on the way, Nezuko suddenly snarls, turning on Tanjiro.",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/liyqZVGyEf5e4TEI2JuKU0aaldI.jpg",
    "vote_average": 8.2,
    "vote_count": 32,
  },
  {
    "air_date": "2019-04-13",
    "episode_number": 2,
    "episode_type": "standard",
    "id": 1732614,
    "name": "Trainer Sakonji Urokodaki",
    "overview": "At Giyu Tomioka's urging, Tanjiro heads for Mt. Sagiri with his sister Nezuko who's been turned into a demon. During the night, Tanjiro catches the smell of blood from inside a temple. He enters, thinking that someone might be hurt, only to come upon a man-eating demon. When the demon attacks, Tanjiro manages to fight back with his hatchet, but the demon's strength is overwhelming. Just as the demon is about to finish him off, Tanjiro is saved by none other than.",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/r2MZH3snLABIpqUPj8YOF9HIaBf.jpg",
    "vote_average": 7.8,
    "vote_count": 30,
  },
  {
    "air_date": "2019-04-20",
    "episode_number": 3,
    "episode_type": "standard",
    "id": 1732615,
    "name": "Sabito and Makomo",
    "overview": "The Demon Slayer Corps... An organization that's been hunting down demons since ancient times. Sakonji Urokodaki starts training Tanjiro for Final Selection, the test for joining the unit. Navigating a mountain riddled with booby traps, dry sword swings, waterfall immersion and breathing techniques... A year later, Urokodaki informs Tanjiro that he has nothing more to teach him, and gives him one last hurdle to overcome in front of a giant boulder.",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/m9sWQLtoU1G5jdHOYUnykin0xxw.jpg",
    "vote_average": 8.1,
    "vote_count": 29
  },
  {
    "air_date": "2019-04-27",
    "episode_number": 4,
    "episode_type": "standard",
    "id": 1732616,
    "name": "Final Selection",
    "overview": "To pass Final Selection, one must survive for seven days on Mt. Fujikasane where demons captured by the Demon Slayers have been imprisoned. So begins the battle for survival between the young swordsmen and the demons. Armed with the breathing techniques and stances he'd learned from Sakonji Urokodaki, Tanjiro slashes demon after demon. His two years of training have not gone to waste. But just then, a morphed demon appears out of nowhere.",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/kH6Ir9EWGoqkTMoiQnx5fJmwY2I.jpg",
    "vote_average": 8.5,
    "vote_count": 28,
  },
  {
    "air_date": "2019-05-04",
    "episode_number": 5,
    "episode_type": "standard",
    "id": 1732617,
    "name": "My Own Steel",
    "overview": "When day breaks, there are only four swordsmen left standing after the seven-day battle. The guides who greet Tanjiro and the other survivors explain the Demon Slayer Corps system. All four are issued uniforms and Kasugai Crows as messengers, after which they must select the ore for their own Nichirin swords. After gazing hard at each lump of ore, and using his keen sense of smell, the one Tanjiro chooses is...",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/fWsUsEVYaOHh6bPkgH7HeQxotmP.jpg",
    "vote_average": 7.7,
    "vote_count": 28,
  },
  {
    "air_date": "2019-05-11",
    "episode_number": 6,
    "episode_type": "standard",
    "id": 1732618,
    "name": "Swordsman Accompanying a Demon",
    "overview": "Tanjiro is now clad in the uniform of the Demon Slayer Corps. His Nichirin Sword on his hip, and Nezuko, now awake, in a special box made by Urokodaki on his back, he heads out for his first assignment. A town to the northwest where girls have been vanishing nightly. There, Tanjiro meets Kazumi, haggard with worry after his girlfriend's been abducted. Though he does catch the scent of a demon nearby, there's just no demon in sight. Tanjiro is sure that a demon is behind this sinister incident...",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/qd0lN2R3wzbUyXbSEQEO19nkGah.jpg",
    "vote_average": 7.9,
    "vote_count": 27,
  },
  {
    "air_date": "2019-05-18",
    "episode_number": 7,
    "episode_type": "standard",
    "id": 1732619,
    "name": "Muzan Kibutsuji",
    "overview": "Now split into three, the demons have driven Tanjiro into a corner. It is then that Nezuko attacks. Now that she’s become a demon herself, she’s no longer so weak that she needs protection. His mind made up, Tanjiro follows one of the demons into the swamp now spreading across the ground. Waiting for him there is...",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/aR1bB3ltg1FjGc6N3xBpiYz7Huo.jpg",
    "vote_average": 8.1,
    "vote_count": 28,
  },
  {
    "air_date": "2019-05-25",
    "episode_number": 8,
    "episode_type": "standard",
    "id": 1732620,
    "name": "The Smell of Enchanting Blood",
    "overview": "The next mission is in Asakusa, Tokyo. Tanjiro is taken aback by the opulent Taisho Era cityscape, but soon picks up the demon’s scent there. His pursuit of the scent leads him to Muzan Kibutsuji. Tanjiro attempts to strike him down. But Kibutsuji transforms a passerby into demon, triggering a commotion. As Tanjiro desperately tries to get things under control, someone appears before him...",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/hnvD3jFov03BLjvGrqTueXZfvwL.jpg",
    "vote_average": 8,
    "vote_count": 26,
  },
  {
    "air_date": "2019-06-01",
    "episode_number": 9,
    "episode_type": "standard",
    "id": 1732621,
    "name": "Temari Demon and Arrow Demon",
    "overview": "It was two demons named Tamayo and Yushiro who came to Tanjiro’s rescue. Using the “Eyeblind” spell, Tamayo guides Tanjiro and Nezuko to her house. There, through his conversation with Tamayo, Tanjiro learns that there is a way to return demons to human form. Just then, two demons in pursuit of Tanjiro locate the house and unleash a furious assault...",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/pMST9IQizKO4EE6P54yFFMBz7vE.jpg",
    "vote_average": 8.2,
    "vote_count": 25,
  },
  {
    "air_date": "2019-06-08",
    "episode_number": 10,
    "episode_type": "standard",
    "id": 1732622,
    "name": "Together Forever",
    "overview": "Tanjiro’s crisis continues. He uses multiple forms of the Water Breathing technique to hold out against Yahaba’s final Blood Demon Art, the \"Kouketsu Arrow.\" Meanwhile, Nezuko and Susamaru are still battling it out. Worried about the outcome, Tamayo unleashes her own Blood Demon Art.",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/nDbVix8vunXKj6zLcVEaxwF7YTq.jpg",
    "vote_average": 8.3,
    "vote_count": 24,
  },
  {
    "air_date": "2019-06-15",
    "episode_number": 11,
    "episode_type": "standard",
    "id": 1732623,
    "name": "Tsuzumi Mansion",
    "overview": "Tanjiro's next destination, according to his Kasugai Crow, is to the south-southeast. On the way, Tanjiro runs into his fellow Final Selection survivor, the swordsman Zenitsu Agatsuma. Tanjiro has a hard time dealing with Zenitsu's passive attitude as they head deep into the mountains. They encounter two children whose older brother was taken away right in front of their house. There, Zenitsu hears the sound of a tsuzumi ringing out from somewhere.",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/xKOewshyBZcisLUWrOQjEGe650L.jpg",
    "vote_average": 7.5,
    "vote_count": 23,
  },
  {
    "air_date": "2019-06-22",
    "episode_number": 12,
    "episode_type": "standard",
    "id": 1732624,
    "name": "The Boar Bares Its Fangs, Zenitsu Sleeps",
    "overview": "Inside the house, where the rooms spin each time the tsuzumi is played, Tanjiro gets separated from Zenitsu Agatsuma. Without Tanjiro by his side, Zenitsu is overcome by fear and despair as he takes Shoichi through the house. Meanwhile, Tanjiro meets the master of the house, the tsuzumi-playing demon, and an odd-looking man wearing a boar’s head mask.",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/qrPsA5eNGH4sPwMImUhOvlShd7U.jpg",
    "vote_average": 8.1,
    "vote_count": 24,
  },
  {
    "air_date": "2019-06-29",
    "episode_number": 13,
    "episode_type": "standard",
    "id": 1798119,
    "name": "Something More Important Than Life",
    "overview": "Every time Kyogai, the master of house, plays his tsuzumi, the room spins and Tanjiro struggles. Debilitated by the fractured bones he sustained in his previous battle, Tanjiro tries to fire himself up as he desperately fights on, but he is overwhelmed by Kyogai's Blood Demon Art. Will he find a way to slice off Kyogai's head?",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/5ixd8rC1tTDHf5kSo5o7hbghpOi.jpg",
    "vote_average": 8.3,
    "vote_count": 24,
  },
  {
    "air_date": "2019-07-06",
    "episode_number": 14,
    "episode_type": "standard",
    "id": 1798120,
    "name": "The House With the Wisteria Family Crest",
    "overview": "After a desperate fight to the death, Tanjiro prevails over Kyogai. He exits the house to find Zenitsu who had escaped earlier. But it is then that he sees the strange circumstances before him... The battered Zenitsu holding the box containing Nezuko in his arms while the man in the boar's head mask stands in the way with two Nichirin Swords drawn.",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/e98IzkyZqU3mUP7f568GenqGQ9v.jpg",
    "vote_average": 7.8,
    "vote_count": 25,
  },
  {
    "air_date": "2019-07-13",
    "episode_number": 15,
    "episode_type": "standard",
    "id": 1798121,
    "name": "Mount Natagumo",
    "overview": "Their next destination is to the north-northwest. Tanjiro and Nezuko head towards Mount Natagumo with Zenitsu and Inosuke. This mountain is covered with spider webs and is swarming with innumerable spiders. Leaving the cowering Zenitsu behind, Tanjiro and Inosuke head up the mountain where they run into fellow Demon Slayers entangled in spider webs.",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/8CNCZfubtFYzvuo4GgIDCSXBYvj.jpg",
    "vote_average": 8,
    "vote_count": 26,
  },
  {
    "air_date": "2019-07-20",
    "episode_number": 16,
    "episode_type": "standard",
    "id": 1798122,
    "name": "Letting Someone Else Go First",
    "overview": "Tanjiro and Inosuke battle the Demon Slayers trapped by spider webs. After slashing the threads and destroying the webs, they head deeper into the mountain. The farther they advance through the forest, the thicker the threads become, and those under their control start moving in ways impossible for a human being. Stopping the Demon Slayers without hurting them isn't going to be easy, but then Tanjiro makes a certain move...",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/swSQtQPgFpqjw3s0LNtUMWyHFnU.jpg",
    "vote_average": 8.2,
    "vote_count": 25,
  },
  {
    "air_date": "2019-07-27",
    "episode_number": 17,
    "episode_type": "standard",
    "id": 1798123,
    "name": "You Must Master a Single Thing",
    "overview": "One of the Twelve Kizuki, a direct subordinate of Muzan Kibutsuji, is here somewhere. When Tanjiro slays the Mother Spider Demon of Mt. Natagumo, he learns that a demon who might hold the key to turning Nezuko back into a human is somewhere in this very forest. With the battered Inosuke in tow, he heads deeper into the forest. Meanwhile, Zenitsu trudges forlornly through the woods only to encounter a spider with a human face.",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/oKOrMhozP1BX6gWiJAcuZVSm6Zd.jpg",
    "vote_average": 8.3,
    "vote_count": 25,
  },
  {
    "air_date": "2019-08-03",
    "episode_number": 18,
    "episode_type": "standard",
    "id": 1798124,
    "name": "A Forged Bond",
    "overview": "Tanjiro and Inosuke face off against the Father Spider Demon of Mt. Natagumo. Tanjiro unleashes an attack, only to get hurled away by the demon's overwhelming power. Landing near a river, he comes upon the young demon Rui torturing the Sister Spider Demon. When Rui calls their bond of terror and hatred \"a family’s bond,\" Tanjiro is enraged. So begins the battle between Rui and Tanjiro.",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/ra7dCRS9E39fnhHieFKF47ldESl.jpg",
    "vote_average": 8.4,
    "vote_count": 26,
  },
  {
    "air_date": "2019-08-10",
    "episode_number": 19,
    "episode_type": "standard",
    "id": 1798125,
    "name": "Hinokami",
    "overview": "Swordsmen in the Demon Slayer Corps known as Hashiras have arrived on Mt. Natagumo. Giyu Tomioka, the Water Hashira, slays the Father Spider Demon with a single strike. Inosuke, thrilled to see such a display of swordsmanship by someone in a totally different league from himself, challenges Giyu to a duel. Meanwhile, Zenitsu lies near death as the poison circulates throughout his body. Just then, the Insect Hashira, Shinobu Kocho appears before him.",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/b4o8DMgM61MJymZMFyR2nRnOifl.jpg",
    "vote_average": 9,
    "vote_count": 31
  },
  {
    "air_date": "2019-08-17",
    "episode_number": 20,
    "episode_type": "standard",
    "id": 1798126,
    "name": "Pretend Family",
    "overview": "When Rui assaults him with his Blood Demon Art, Tanjiro braces himself for certain death. As his life flashes before his eyes, he suddenly remembers his father's dance, the kagura, and unleashes a new, non-Water Breathing attack. Hinokami Kagura Dance. Knowing that he’ll be receiving a simultaneous blow from the demon, he uses his new move to slice off Rui’s head. As Tanjiro crawls towards Nezuko, who lies on the ground, riddled with wounds, someone appears before him.",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/zEBhEj2Dt58vqAUsEWv6DOCz5RJ.jpg",
    "vote_average": 8.2,
    "vote_count": 25
  },
  {
    "air_date": "2019-08-24",
    "episode_number": 21,
    "episode_type": "standard",
    "id": 1798127,
    "name": "Against Corps Rules",
    "overview": "Seeing Tanjiro try to protect Nezuko even as he collapses triggers memories of Rui’s own past. Once a sickly boy, he became a demon after meeting Muzan Kibutsuji who gave him a share of his blood. But after he turns into a demon, his own parents try to kill him. Ever since then, he has been searching for a family. Seeking a bond that he can never hope to acquire...",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/g3jzSZOzqaH6VD23tmIqRQLtLoF.jpg",
    "vote_average": 8.2,
    "vote_count": 24
  },
  {
    "air_date": "2019-08-31",
    "episode_number": 22,
    "episode_type": "standard",
    "id": 1798128,
    "name": "Master of the Mansion",
    "overview": "After the battle is over, Tanjiro and Nezuko are taken to the Demon Slayer Corps headquarters. This is where the Hashira Meeting between the Corps leader, Ubuyashiki, and the Hashiras, the most powerful swordsmen in the Corps, is to be held. The Hashiras censure Tanjiro for violating the Demon Slayer Corps by protecting a demon. And then, the Wind Hashira, Sanemi Shinazugawa, raises his sword against Nezuko...",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/2bo6M1fLHXz47b3NoW3Y5zesTKB.jpg",
    "vote_average": 7.9,
    "vote_count": 23
  },
  {
    "air_date": "2019-09-07",
    "episode_number": 23,
    "episode_type": "standard",
    "id": 1798129,
    "name": "Hashira Meeting",
    "overview": "Ubuyashiki, the leader of the Demon Slayer Corps, finally appears before Tanjiro. He tells him that he will allow Tanjiro and Nezuko to join the Corps. But the Hashiras are unable to accept this decision right away. The Wind Hashira, Sanemi Shinazugawa, slashes his own arm and taunts Nezuko with his blood, trying to get her to show her true colors as a demon.",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/gdlEXQbUuVtIzKxuOMWd2BhT4n8.jpg",
    "vote_average": 7.8,
    "vote_count": 25
  },
  {
    "air_date": "2019-09-14",
    "episode_number": 24,
    "episode_type": "standard",
    "id": 1798130,
    "name": "Rehabilitation Training",
    "overview": "The injured Tanjiro, Zenitsu and Inosuke are sent to the home of the Insect Hashira, Shinobu Kocho, for treatment. Two weeks later, Tanjiro and Inosuke start rehabilitation training. But the drills are brutal, and they find themselves broken in spirit. Unaware of the grueling regimen, Zenitsu joins them late and is visibly enthusiastic in front of girls, but...",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/hhZsnP34Tjx568RJwSTN9nkkCcX.jpg",
    "vote_average": 7.7,
    "vote_count": 23
  },
  {
    "air_date": "2019-09-21",
    "episode_number": 25,
    "episode_type": "standard",
    "id": 1798131,
    "name": "Tsuguko, Kanao Tsuyuri",
    "overview": "Tanjiro, who's undergoing rehabilitation training at the Butterfly Mansion, works hard to keep up his Total Concentration Breathing techniques all day long. Though at first, he's helpless against Kanao, a swordswoman in his class who's training him, he slowly but surely begins to make some headway. Seeing Tanjiro devote himself to training every single day, Zenitsu and Inosuke resume training as well, but...",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/4VmgnTSJvOPbfy7k51t94T4q88e.jpg",
    "vote_average": 7.6,
    "vote_count": 21
  },
  {
    "air_date": "2019-09-28",
    "episode_number": 26,
    "episode_type": "finale",
    "id": 1798132,
    "name": "New Mission",
    "overview": "As Tanjiro and the others are devoted to their rehabilitation training, the absolute master of the demons, Muzan Kibutsuji, gathers the Lower Ranks of the Twelve Kizuki. The demons, too, are preparing to make their next move. As training draws to a close, Tanjiro has improved to the point where he can fight on equal terms with Kanao. Just then, he receives word of a new mission from his Kasugai Crow.",
    "production_code": "",
    "runtime": 23,
    "season_number": 1,
    "show_id": 85937,
    "still_path": "/ooZNrd1lFth6NVzToRd8MOKuNGK.jpg",
    "vote_average": 8.2,
    "vote_count": 24
  }
]