export const mockContens = [
  {
    "backdrop_path": "/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg",
    "id": 786892,
    "title": "Furiosa: A Mad Max Saga",
    "original_title": "Furiosa: A Mad Max Saga",
    "overview": "As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.",
    "poster_path": "/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      28,
      12,
      878
    ],
    "popularity": 4115.719,
    "release_date": "2024-05-22",
    "video": false,
    "vote_average": 7.712,
    "vote_count": 1680
  },
  {
    "backdrop_path": "/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg",
    "id": 1022789,
    "title": "Inside Out 2",
    "original_title": "Inside Out 2",
    "overview": "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
    "poster_path": "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      16,
      10751,
      12,
      35
    ],
    "popularity": 4128.506,
    "release_date": "2024-06-11",
    "video": false,
    "vote_average": 7.711,
    "vote_count": 1285
  },
  {
    "backdrop_path": "/nxxCPRGTzxUH8SFMrIsvMmdxHti.jpg",
    "id": 639720,
    "title": "IF",
    "original_title": "IF",
    "overview": "A young girl who goes through a difficult experience begins to see everyone's imaginary friends who have been left behind as their real-life friends have grown up.",
    "poster_path": "/xbKFv4KF3sVYuWKllLlwWDmuZP7.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      35,
      14,
      10751
    ],
    "popularity": 655.437,
    "release_date": "2024-05-08",
    "video": false,
    "vote_average": 7.395,
    "vote_count": 527
  },
  {
    "backdrop_path": "/whnFKx0Y54Ktg6o2TiwbnQfXdZf.jpg",
    "id": 1086747,
    "title": "The Watchers",
    "original_title": "The Watchers",
    "overview": "A young artist gets stranded in an extensive, immaculate forest in western Ireland, where, after finding shelter, she becomes trapped alongside three strangers, stalked by mysterious creatures each night.",
    "poster_path": "/vZVEUPychdvZLrTNwWErr9xZFmu.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      27,
      9648,
      14
    ],
    "popularity": 867.31,
    "release_date": "2024-06-06",
    "video": false,
    "vote_average": 6.522,
    "vote_count": 341
  },
  {
    "backdrop_path": "/bWg5fnzjZOtFwOz4cDHWHtvsTPU.jpg",
    "id": 762441,
    "title": "A Quiet Place: Day One",
    "original_title": "A Quiet Place: Day One",
    "overview": "As New York City is invaded by alien creatures who hunt by sound, a woman named Sam fights to survive.",
    "poster_path": "/yrpPYKijwdMHyTGIOd1iK1h0Xno.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      27,
      878,
      53
    ],
    "popularity": 926.797,
    "release_date": "2024-06-26",
    "video": false,
    "vote_average": 6.976,
    "vote_count": 231
  },
  {
    "backdrop_path": "/75nSb1fbWooipwcSU5bUttiOriI.jpg",
    "id": 508883,
    "title": "The Boy and the Heron",
    "original_title": "君たちはどう生きるか",
    "overview": "While the Second World War rages, the teenage Mahito, haunted by his mother's tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy's mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the \"long-awaited one.\"",
    "poster_path": "/f4oZTcfGrVTXKTWg157AwikXqmP.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "ja",
    "genre_ids": [
      16,
      12,
      14
    ],
    "popularity": 235.278,
    "release_date": "2023-07-14",
    "video": false,
    "vote_average": 7.484,
    "vote_count": 1362
  },
  {
    "backdrop_path": "/rrwt0u1rW685u9bJ9ougg5HJEHC.jpg",
    "id": 280180,
    "title": "Beverly Hills Cop: Axel F",
    "original_title": "Beverly Hills Cop: Axel F",
    "overview": "After his daughter's life is threatened, wisecracking detective Axel Foley teams up with a new partner and some old pals to turn up the heat on a conspiracy.",
    "poster_path": "/zszRKfzjM5jltiq8rk6rasKVpUv.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      28,
      35,
      80
    ],
    "popularity": 158.934,
    "release_date": "2024-06-20",
    "video": false,
    "vote_average": 7.329,
    "vote_count": 70
  },
  {
    "backdrop_path": "/fDmci71SMkfZM8RnCuXJVDPaSdE.jpg",
    "id": 519182,
    "title": "Despicable Me 4",
    "original_title": "Despicable Me 4",
    "overview": "Gru and Lucy and their girls — Margo, Edith and Agnes — welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, and the family is forced to go on the run.",
    "poster_path": "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      16,
      10751,
      35,
      28
    ],
    "popularity": 1256.95,
    "release_date": "2024-06-20",
    "video": false,
    "vote_average": 8.3,
    "vote_count": 75
  },
  {
    "backdrop_path": "/aATi2PtaOQCVAquCym6OU0Z4FjY.jpg",
    "id": 704673,
    "title": "Trigger Warning",
    "original_title": "Trigger Warning",
    "overview": "A Special Forces commando uncovers a dangerous conspiracy when she returns to her hometown looking for answers into her beloved father's death.",
    "poster_path": "/6XJM3C47iGOK9nFU6yLFCSf4U5c.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      28,
      80,
      53
    ],
    "popularity": 1205.913,
    "release_date": "2024-06-20",
    "video": false,
    "vote_average": 5.778,
    "vote_count": 239
  },
  {
    "backdrop_path": "/jvPMJ2zM92jfXxVEFsqP1MMrLaO.jpg",
    "id": 823464,
    "title": "Godzilla x Kong: The New Empire",
    "original_title": "Godzilla x Kong: The New Empire",
    "overview": "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
    "poster_path": "/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      878,
      28,
      12
    ],
    "popularity": 1029.737,
    "release_date": "2024-03-27",
    "video": false,
    "vote_average": 7.212,
    "vote_count": 3002
  },
  {
    "backdrop_path": "/ngLxW9WqQAkTCBTcjOSt2Pnz5qZ.jpg",
    "id": 987686,
    "title": "A Family Affair",
    "original_title": "A Family Affair",
    "overview": "The only thing worse than being the assistant to a high-maintenance movie star who doesn't take you seriously? Finding out he's smitten with your mom.",
    "poster_path": "/l0CaVyqnTsWwNd4hWsrLNEk1Wjd.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      10749,
      35
    ],
    "popularity": 711.51,
    "release_date": "2024-06-27",
    "video": false,
    "vote_average": 6.253,
    "vote_count": 168
  },
  {
    "backdrop_path": "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    "id": 693134,
    "title": "Dune: Part Two",
    "original_title": "Dune: Part Two",
    "overview": "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
    "poster_path": "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      878,
      12
    ],
    "popularity": 413.319,
    "release_date": "2024-02-27",
    "video": false,
    "vote_average": 8.2,
    "vote_count": 4726
  },
  {
    "backdrop_path": "/d4P97PFMG5UKyZyvRn5kIiNMBxn.jpg",
    "id": 974635,
    "title": "Hit Man",
    "original_title": "Hit Man",
    "overview": "A mild-mannered professor moonlighting as a fake hit man in police stings ignites a chain reaction of trouble when he falls for a potential client.",
    "poster_path": "/1126gjlBf4hTm9Sgf0ox3LGVEBt.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      80,
      35,
      10749
    ],
    "popularity": 234.383,
    "release_date": "2024-05-16",
    "video": false,
    "vote_average": 7.047,
    "vote_count": 467
  },
  {
    "backdrop_path": "/dvBCdCohwWbsP5qAaglOXagDMtk.jpg",
    "id": 533535,
    "title": "Deadpool & Wolverine",
    "original_title": "Deadpool & Wolverine",
    "overview": "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
    "poster_path": "/jbwYaoYWZwxtPP76AZnfYKQjCEB.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      878,
      28,
      35
    ],
    "popularity": 357.03,
    "release_date": "2024-07-24",
    "video": false,
    "vote_average": 0,
    "vote_count": 0
  },
  {
    "backdrop_path": "/gRApXuxWmO2forYTuTmcz5RaNUV.jpg",
    "id": 573435,
    "title": "Bad Boys: Ride or Die",
    "original_title": "Bad Boys: Ride or Die",
    "overview": "After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.",
    "poster_path": "/nP6RliHjxsz4irTKsxe8FRhKZYl.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      28,
      80,
      53,
      35
    ],
    "popularity": 1329.004,
    "release_date": "2024-06-05",
    "video": false,
    "vote_average": 7.023,
    "vote_count": 475
  },
  {
    "backdrop_path": "/j29ekbcLpBvxnGk6LjdTc2EI5SA.jpg",
    "id": 150540,
    "title": "Inside Out",
    "original_title": "Inside Out",
    "overview": "When 11-year-old Riley moves to a new city, her Emotions team up to help her through the transition. Joy, Fear, Anger, Disgust and Sadness work together, but when Joy and Sadness get lost, they must journey through unfamiliar places to get back home.",
    "poster_path": "/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      16,
      10751,
      12,
      18,
      35
    ],
    "popularity": 1320.405,
    "release_date": "2015-06-17",
    "video": false,
    "vote_average": 7.915,
    "vote_count": 21027
  },
  {
    "backdrop_path": "/H5HjE7Xb9N09rbWn1zBfxgI8uz.jpg",
    "id": 746036,
    "title": "The Fall Guy",
    "original_title": "The Fall Guy",
    "overview": "Fresh off an almost career-ending accident, stuntman Colt Seavers has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job.",
    "poster_path": "/aBkqu7EddWK7qmY4grL4I6edx2h.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      28,
      35
    ],
    "popularity": 519.222,
    "release_date": "2024-04-24",
    "video": false,
    "vote_average": 7.266,
    "vote_count": 1460
  },
  {
    "backdrop_path": "/1r1dWa9yf1LeSLfkOfkSqxmWHdK.jpg",
    "id": 967847,
    "title": "Ghostbusters: Frozen Empire",
    "original_title": "Ghostbusters: Frozen Empire",
    "overview": "When the discovery of an ancient artifact unleashes an evil force, Ghostbusters new and old must join forces to protect their home and save the world from a second Ice Age.",
    "poster_path": "/e1J2oNzSBdou01sUvriVuoYp0pJ.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      14,
      12,
      35
    ],
    "popularity": 224.752,
    "release_date": "2024-03-20",
    "video": false,
    "vote_average": 6.694,
    "vote_count": 1062
  },
  {
    "backdrop_path": "/z121dSTR7PY9KxKuvwiIFSYW8cf.jpg",
    "id": 929590,
    "title": "Civil War",
    "original_title": "Civil War",
    "overview": "In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.",
    "poster_path": "/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      10752,
      28,
      18
    ],
    "popularity": 915.977,
    "release_date": "2024-04-10",
    "video": false,
    "vote_average": 7.011,
    "vote_count": 1779
  },
  {
    "backdrop_path": "/h7V8yzSnPYkNEvAqmeYHcfJ6rbk.jpg",
    "id": 1214509,
    "title": "In a Violent Nature",
    "original_title": "In a Violent Nature",
    "overview": "The enigmatic resurrection, rampage, and retribution of an undead monster in a remote wilderness unleashes an iconic new killer after a locket is removed from a collapsed fire tower that entombed its rotting corpse.",
    "poster_path": "/o5pcDZaA9Up0X612os34JNCRX6j.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [
      27,
      53
    ],
    "popularity": 207.523,
    "release_date": "2024-05-31",
    "video": false,
    "vote_average": 5.8,
    "vote_count": 41
  }
]